### ISSUE TITLE
Tool used for OTP

### ISSUE THREAD

**Issue by tusharnankani** [gauravraj0510/PopChat#2]
Hi @gauravraj0510!

For `sign in with phone number` - Could you tell which tool have you used? 
And if it is paid or not? 

Also, could you tell me how did you implement the auto - fill OTP system?
I am just very eager and interested! Hope you don't mind! ^_^

Thanks,
Tushar Nankani

**Comment by 2tanayk** [comment]
> Hi @gauravraj0510!
> 
> For `sign in with phone number` - Could you tell which tool have you used?
> And if it is paid or not?
> 
> Also, could you tell me how did you implement the auto - fill OTP system?
> I am just very eager and interested! Hope you don't mind! ^_^
> 
> Thanks,
> Tushar Nankani

Ig he has used firebase for signing in with phone no,you can too do this....just create a firebase project and read the docs!

**Comment by 2tanayk** [comment]
firebase authentication to be appropriate @tusharnankani

**Comment by gauravraj0510** [comment]
name of the tool is Firebase AUTH UI its like an API only by firebase

**Comment by tusharnankani** [comment]
So, Firebase handles everything? From sending message for OTP, till auto filling the OTP in the system? @gauravraj0510

**Comment by gauravraj0510** [comment]
Yes everything no manual fuss

**Comment by gauravraj0510** [comment]
Shall i close this issue Tushar ? Or there's something more you would like to know?

**Comment by tusharnankani** [comment]
Alright! That's great. 

Thanks for answering the question. @gauravraj0510 @2tanayk 
I am closing this issue.

Also, try labelling the issues, example: <kbd>enhancement</kbd>, <kbd>question</kbd> or a <kbd>bug</kbd> etc.
Will help, when there are a lot of issues. ^_^
