### ISSUE TITLE
Increase padding in text input.

### ISSUE THREAD

**Issue by tusharnankani** [gauravraj0510/PopChat#4]
Hi!

- Could you increase the `padding` for the text-input? So that text isn't covered.

![photo_2020-08-05_17-52-58](https://user-images.githubusercontent.com/61280281/89412466-c6b94500-d744-11ea-9de8-5883b2f28471.jpg)

Thanks,
Tushar Nankani 
🤗

**Comment by gauravraj0510** [comment]
Alright will definitely update this. Thanks a lot!

**Comment by gauravraj0510** [comment]
Fixed.
